server:
  port: 1801

eureka:
  instance:
    hostname: eureka.love-baby.vip
    status-page-url: http://eureka.love-baby.vip/actuator/info
    health-check-url: http://eureka.love-baby.vip/actuator/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/
spring:
  application:
    name: love-baby-eureka